[2023-07-21 20:03:49,868] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_digitalskola_finalproject.insert_data_to_dim_case manual__2023-07-21T20:03:45.325181+00:00 [queued]>
[2023-07-21 20:03:49,939] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_digitalskola_finalproject.insert_data_to_dim_case manual__2023-07-21T20:03:45.325181+00:00 [queued]>
[2023-07-21 20:03:50,030] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-21 20:03:50,038] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-21 20:03:50,047] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-21 20:03:50,127] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_data_to_dim_case> on 2023-07-21 20:03:45.325181+00:00
[2023-07-21 20:03:50,158] {standard_task_runner.py:52} INFO - Started process 3257 to run task
[2023-07-21 20:03:50,192] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_digitalskola_finalproject', 'insert_data_to_dim_case', 'manual__2023-07-21T20:03:45.325181+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_digitalskola_finalproject.py', '--cfg-path', '/tmp/tmpkdklpb6f', '--error-file', '/tmp/tmp_3c8ngbc']
[2023-07-21 20:03:50,206] {standard_task_runner.py:80} INFO - Job 53: Subtask insert_data_to_dim_case
[2023-07-21 20:03:50,923] {task_command.py:369} INFO - Running <TaskInstance: dag_digitalskola_finalproject.insert_data_to_dim_case manual__2023-07-21T20:03:45.325181+00:00 [running]> on host 34be34978432
[2023-07-21 20:03:51,443] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_digitalskola_finalproject
AIRFLOW_CTX_TASK_ID=insert_data_to_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T20:03:45.325181+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-21T20:03:45.325181+00:00
[2023-07-21 20:03:51,455] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_digitalskola_finalproject.py", line 55, in insert_data_to_dim_case
    transformer.insert_data_to_dim_case()
  File "/opt/airflow/dags/modules/transformer.py", line 74, in insert_data_to_dim_case
    'id': range[1:len(temp)+1],
TypeError: 'type' object is not subscriptable
[2023-07-21 20:03:51,552] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_digitalskola_finalproject, task_id=insert_data_to_dim_case, execution_date=20230721T200345, start_date=20230721T200349, end_date=20230721T200351
[2023-07-21 20:03:51,654] {standard_task_runner.py:97} ERROR - Failed to execute job 53 for task insert_data_to_dim_case ('type' object is not subscriptable; 3257)
[2023-07-21 20:03:51,721] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-21 20:03:51,831] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
