[2023-07-21 23:08:29,661] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_digitalskola_finalproject.insert_data_to_district_daily manual__2023-07-21T23:08:26.087655+00:00 [queued]>
[2023-07-21 23:08:29,744] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_digitalskola_finalproject.insert_data_to_district_daily manual__2023-07-21T23:08:26.087655+00:00 [queued]>
[2023-07-21 23:08:29,747] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-21 23:08:29,749] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-21 23:08:29,751] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-21 23:08:29,844] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_data_to_district_daily> on 2023-07-21 23:08:26.087655+00:00
[2023-07-21 23:08:29,866] {standard_task_runner.py:52} INFO - Started process 5095 to run task
[2023-07-21 23:08:29,998] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_digitalskola_finalproject', 'insert_data_to_district_daily', 'manual__2023-07-21T23:08:26.087655+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dag_digitalskola_finalproject.py', '--cfg-path', '/tmp/tmpzi_30hg5', '--error-file', '/tmp/tmpwrj553pq']
[2023-07-21 23:08:30,017] {standard_task_runner.py:80} INFO - Job 83: Subtask insert_data_to_district_daily
[2023-07-21 23:08:30,233] {task_command.py:369} INFO - Running <TaskInstance: dag_digitalskola_finalproject.insert_data_to_district_daily manual__2023-07-21T23:08:26.087655+00:00 [running]> on host 34be34978432
[2023-07-21 23:08:30,533] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_digitalskola_finalproject
AIRFLOW_CTX_TASK_ID=insert_data_to_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T23:08:26.087655+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-21T23:08:26.087655+00:00
[2023-07-21 23:08:30,777] {transformer.py:27} INFO - GET DATA FROM TABLE covid_jabar SUCCESS
[2023-07-21 23:08:30,920] {transformer.py:33} INFO - GET DATA FROM TABLE dim_case SUCCESS
[2023-07-21 23:08:30,957] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_digitalskola_finalproject.py", line 58, in insert_data_to_district_daily
    transformer.insert_data_to_district_daily()
  File "/opt/airflow/dags/modules/transformer.py", line 173, in insert_data_to_district_daily
    data = data.melt(id_vars=['tanggal', 'kode_kab'], var_name='status', value_name='total').sort_values(['tanggal','kode_kab'])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 8346, in melt
    ignore_index=ignore_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/melt.py", line 83, in melt
    "The following 'id_vars' are not present "
KeyError: "The following 'id_vars' are not present in the DataFrame: ['kode_kab']"
[2023-07-21 23:08:31,004] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_digitalskola_finalproject, task_id=insert_data_to_district_daily, execution_date=20230721T230826, start_date=20230721T230829, end_date=20230721T230831
[2023-07-21 23:08:31,059] {standard_task_runner.py:97} ERROR - Failed to execute job 83 for task insert_data_to_district_daily ("The following 'id_vars' are not present in the DataFrame: ['kode_kab']"; 5095)
[2023-07-21 23:08:31,115] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-21 23:08:31,226] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
